var test_stimuli = [
  {
    Illusion_Type: "Delboeuf",
    Illusion_Strength: -1.0,
    Difference: -1.0,
    stimulus: "stimuli/Delboeuf_str-1.0_diff-1.0.png",
    data: { screen: "test", block: "Delboeuf", correct_response: "arrowright" },
  },
  {
    Illusion_Type: "Delboeuf",
    Illusion_Strength: -1.0,
    Difference: -0.33333333333333337,
    stimulus: "stimuli/Delboeuf_str-1.0_diff-0.33.png",
    data: { screen: "test", block: "Delboeuf", correct_response: "arrowright" },
  },
  {
    Illusion_Type: "Delboeuf",
    Illusion_Strength: -1.0,
    Difference: 0.33333333333333326,
    stimulus: "stimuli/Delboeuf_str-1.0_diff0.33.png",
    data: { screen: "test", block: "Delboeuf", correct_response: "arrowleft" },
  },
  {
    Illusion_Type: "Delboeuf",
    Illusion_Strength: -1.0,
    Difference: 1.0,
    stimulus: "stimuli/Delboeuf_str-1.0_diff1.0.png",
    data: { screen: "test", block: "Delboeuf", correct_response: "arrowleft" },
  },
  {
    Illusion_Type: "Delboeuf",
    Illusion_Strength: -0.33333333333333337,
    Difference: -1.0,
    stimulus: "stimuli/Delboeuf_str-0.33_diff-1.0.png",
    data: { screen: "test", block: "Delboeuf", correct_response: "arrowright" },
  },
  {
    Illusion_Type: "Delboeuf",
    Illusion_Strength: -0.33333333333333337,
    Difference: -0.33333333333333337,
    stimulus: "stimuli/Delboeuf_str-0.33_diff-0.33.png",
    data: { screen: "test", block: "Delboeuf", correct_response: "arrowright" },
  },
  {
    Illusion_Type: "Delboeuf",
    Illusion_Strength: -0.33333333333333337,
    Difference: 0.33333333333333326,
    stimulus: "stimuli/Delboeuf_str-0.33_diff0.33.png",
    data: { screen: "test", block: "Delboeuf", correct_response: "arrowleft" },
  },
  {
    Illusion_Type: "Delboeuf",
    Illusion_Strength: -0.33333333333333337,
    Difference: 1.0,
    stimulus: "stimuli/Delboeuf_str-0.33_diff1.0.png",
    data: { screen: "test", block: "Delboeuf", correct_response: "arrowleft" },
  },
  {
    Illusion_Type: "Delboeuf",
    Illusion_Strength: 0.33333333333333326,
    Difference: -1.0,
    stimulus: "stimuli/Delboeuf_str0.33_diff-1.0.png",
    data: { screen: "test", block: "Delboeuf", correct_response: "arrowright" },
  },
  {
    Illusion_Type: "Delboeuf",
    Illusion_Strength: 0.33333333333333326,
    Difference: -0.33333333333333337,
    stimulus: "stimuli/Delboeuf_str0.33_diff-0.33.png",
    data: { screen: "test", block: "Delboeuf", correct_response: "arrowright" },
  },
  {
    Illusion_Type: "Delboeuf",
    Illusion_Strength: 0.33333333333333326,
    Difference: 0.33333333333333326,
    stimulus: "stimuli/Delboeuf_str0.33_diff0.33.png",
    data: { screen: "test", block: "Delboeuf", correct_response: "arrowleft" },
  },
  {
    Illusion_Type: "Delboeuf",
    Illusion_Strength: 0.33333333333333326,
    Difference: 1.0,
    stimulus: "stimuli/Delboeuf_str0.33_diff1.0.png",
    data: { screen: "test", block: "Delboeuf", correct_response: "arrowleft" },
  },
  {
    Illusion_Type: "Delboeuf",
    Illusion_Strength: 1.0,
    Difference: -1.0,
    stimulus: "stimuli/Delboeuf_str1.0_diff-1.0.png",
    data: { screen: "test", block: "Delboeuf", correct_response: "arrowright" },
  },
  {
    Illusion_Type: "Delboeuf",
    Illusion_Strength: 1.0,
    Difference: -0.33333333333333337,
    stimulus: "stimuli/Delboeuf_str1.0_diff-0.33.png",
    data: { screen: "test", block: "Delboeuf", correct_response: "arrowright" },
  },
  {
    Illusion_Type: "Delboeuf",
    Illusion_Strength: 1.0,
    Difference: 0.33333333333333326,
    stimulus: "stimuli/Delboeuf_str1.0_diff0.33.png",
    data: { screen: "test", block: "Delboeuf", correct_response: "arrowleft" },
  },
  {
    Illusion_Type: "Delboeuf",
    Illusion_Strength: 1.0,
    Difference: 1.0,
    stimulus: "stimuli/Delboeuf_str1.0_diff1.0.png",
    data: { screen: "test", block: "Delboeuf", correct_response: "arrowleft" },
  },
  {
    Illusion_Type: "Ebbinghaus",
    Illusion_Strength: -1.0,
    Difference: -1.0,
    stimulus: "stimuli/Ebbinghaus_str-1.0_diff-1.0.png",
    data: {
      screen: "test",
      block: "Ebbinghaus",
      correct_response: "arrowright",
    },
  },
  {
    Illusion_Type: "Ebbinghaus",
    Illusion_Strength: -1.0,
    Difference: -0.33333333333333337,
    stimulus: "stimuli/Ebbinghaus_str-1.0_diff-0.33.png",
    data: {
      screen: "test",
      block: "Ebbinghaus",
      correct_response: "arrowright",
    },
  },
  {
    Illusion_Type: "Ebbinghaus",
    Illusion_Strength: -1.0,
    Difference: 0.33333333333333326,
    stimulus: "stimuli/Ebbinghaus_str-1.0_diff0.33.png",
    data: {
      screen: "test",
      block: "Ebbinghaus",
      correct_response: "arrowleft",
    },
  },
  {
    Illusion_Type: "Ebbinghaus",
    Illusion_Strength: -1.0,
    Difference: 1.0,
    stimulus: "stimuli/Ebbinghaus_str-1.0_diff1.0.png",
    data: {
      screen: "test",
      block: "Ebbinghaus",
      correct_response: "arrowleft",
    },
  },
  {
    Illusion_Type: "Ebbinghaus",
    Illusion_Strength: -0.33333333333333337,
    Difference: -1.0,
    stimulus: "stimuli/Ebbinghaus_str-0.33_diff-1.0.png",
    data: {
      screen: "test",
      block: "Ebbinghaus",
      correct_response: "arrowright",
    },
  },
  {
    Illusion_Type: "Ebbinghaus",
    Illusion_Strength: -0.33333333333333337,
    Difference: -0.33333333333333337,
    stimulus: "stimuli/Ebbinghaus_str-0.33_diff-0.33.png",
    data: {
      screen: "test",
      block: "Ebbinghaus",
      correct_response: "arrowright",
    },
  },
  {
    Illusion_Type: "Ebbinghaus",
    Illusion_Strength: -0.33333333333333337,
    Difference: 0.33333333333333326,
    stimulus: "stimuli/Ebbinghaus_str-0.33_diff0.33.png",
    data: {
      screen: "test",
      block: "Ebbinghaus",
      correct_response: "arrowleft",
    },
  },
  {
    Illusion_Type: "Ebbinghaus",
    Illusion_Strength: -0.33333333333333337,
    Difference: 1.0,
    stimulus: "stimuli/Ebbinghaus_str-0.33_diff1.0.png",
    data: {
      screen: "test",
      block: "Ebbinghaus",
      correct_response: "arrowleft",
    },
  },
  {
    Illusion_Type: "Ebbinghaus",
    Illusion_Strength: 0.33333333333333326,
    Difference: -1.0,
    stimulus: "stimuli/Ebbinghaus_str0.33_diff-1.0.png",
    data: {
      screen: "test",
      block: "Ebbinghaus",
      correct_response: "arrowright",
    },
  },
  {
    Illusion_Type: "Ebbinghaus",
    Illusion_Strength: 0.33333333333333326,
    Difference: -0.33333333333333337,
    stimulus: "stimuli/Ebbinghaus_str0.33_diff-0.33.png",
    data: {
      screen: "test",
      block: "Ebbinghaus",
      correct_response: "arrowright",
    },
  },
  {
    Illusion_Type: "Ebbinghaus",
    Illusion_Strength: 0.33333333333333326,
    Difference: 0.33333333333333326,
    stimulus: "stimuli/Ebbinghaus_str0.33_diff0.33.png",
    data: {
      screen: "test",
      block: "Ebbinghaus",
      correct_response: "arrowleft",
    },
  },
  {
    Illusion_Type: "Ebbinghaus",
    Illusion_Strength: 0.33333333333333326,
    Difference: 1.0,
    stimulus: "stimuli/Ebbinghaus_str0.33_diff1.0.png",
    data: {
      screen: "test",
      block: "Ebbinghaus",
      correct_response: "arrowleft",
    },
  },
  {
    Illusion_Type: "Ebbinghaus",
    Illusion_Strength: 1.0,
    Difference: -1.0,
    stimulus: "stimuli/Ebbinghaus_str1.0_diff-1.0.png",
    data: {
      screen: "test",
      block: "Ebbinghaus",
      correct_response: "arrowright",
    },
  },
  {
    Illusion_Type: "Ebbinghaus",
    Illusion_Strength: 1.0,
    Difference: -0.33333333333333337,
    stimulus: "stimuli/Ebbinghaus_str1.0_diff-0.33.png",
    data: {
      screen: "test",
      block: "Ebbinghaus",
      correct_response: "arrowright",
    },
  },
  {
    Illusion_Type: "Ebbinghaus",
    Illusion_Strength: 1.0,
    Difference: 0.33333333333333326,
    stimulus: "stimuli/Ebbinghaus_str1.0_diff0.33.png",
    data: {
      screen: "test",
      block: "Ebbinghaus",
      correct_response: "arrowleft",
    },
  },
  {
    Illusion_Type: "Ebbinghaus",
    Illusion_Strength: 1.0,
    Difference: 1.0,
    stimulus: "stimuli/Ebbinghaus_str1.0_diff1.0.png",
    data: {
      screen: "test",
      block: "Ebbinghaus",
      correct_response: "arrowleft",
    },
  },
];
